# Generated by Django 3.2.5 on 2021-07-17 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='downvote',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='note',
            name='upvote',
            field=models.BigIntegerField(default=0),
        ),
    ]
