# Generated by Django 3.2.5 on 2021-07-18 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0002_auto_20210718_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.TextField(max_length=100),
        ),
    ]
