# Generated by Django 3.2.5 on 2021-07-19 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0003_alter_note_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDownVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(default=0)),
                ('note_id', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserUpVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(default=0)),
                ('note_id', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='note',
            old_name='downvote',
            new_name='down_vote',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='upvote',
            new_name='up_vote',
        ),
        migrations.AddField(
            model_name='note',
            name='username',
            field=models.TextField(default='user_default_name', max_length=100),
        ),
    ]
